# Generated by Django 2.0.3 on 2018-04-01 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frbblog', '0002_auto_20180401_0707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
